apiVersion: k8s.opendatahub.io.opendatahub.io/v1alpha1
kind: ModelRegistry
metadata:
  labels:
    app.kubernetes.io/name: modelregistry
    app.kubernetes.io/instance: modelregistry-sample
    app.kubernetes.io/part-of: model-registry-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: model-registry-operator
  name: modelregistry-sample
spec:
  # TODO(user): Add fields here
